//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bib2.Models
{
    using System;
    using System.Collections.Generic;   
    using System.ComponentModel.DataAnnotations;
  


    public partial class mlib
    {
        [Display(Name = "Código")]
        public int idLibro { get; set; }
        [Display(Name = "Título")]
        public string titulo { get; set; }
        [Display(Name = "Autor")]
        public string autor { get; set; }
        public string editorial { get; set; }
        public string coleccion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        [Display(Name = "Temática")]
        public string tema { get; set; }
        [Display(Name = "Cálif.")]
        public Nullable<int> calificacion { get; set; }
        [Display(Name = "Páginas")]
        public Nullable<int> paginas { get; set; }
        [Display(Name = "Opinión")]
        public string comentario { get; set; }
        public string prestamo { get; set; }
        public Nullable<System.DateTime> fecha_prestamo { get; set; }
        public Nullable<int> numobras { get; set; }
        public string origen { get; set; }
        public int CodAutor { get; set; }
    }
}
