//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bib2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urls
    {
        public int tipo { get; set; }
        public int codigo_padre { get; set; }
        public string direccion { get; set; }
        public string descripcion { get; set; }
    }
}
